# Generated by Django 5.1.2 on 2024-11-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initializing_custom_user_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
