# Generated by Django 5.1.2 on 2024-11-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDim',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('link', models.TextField()),
                ('link_google', models.TextField()),
                ('thumbnail', models.TextField()),
            ],
            options={
                'db_table': 'company_dim',
            },
        ),
        migrations.CreateModel(
            name='SkillsDim',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'skills_dim',
            },
        ),
        migrations.CreateModel(
            name='JobPostingsFact',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title_short', models.CharField(max_length=255)),
                ('job_title', models.TextField()),
                ('job_location', models.TextField()),
                ('job_via', models.TextField()),
                ('job_schedule_type', models.TextField()),
                ('job_work_from_home', models.BooleanField()),
                ('search_location', models.TextField()),
                ('job_posted_date', models.DateTimeField()),
                ('job_no_degree_mention', models.BooleanField()),
                ('job_health_insurance', models.BooleanField()),
                ('job_country', models.TextField()),
                ('salary_rate', models.TextField()),
                ('salary_year_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_hour_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_postings.companydim')),
            ],
            options={
                'db_table': 'job_postings_fact',
            },
        ),
        migrations.CreateModel(
            name='SkillsJobDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_postings.jobpostingsfact')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_postings.skillsdim')),
            ],
            options={
                'db_table': 'skills_job_dim',
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
