# Generated by Django 5.1.2 on 2024-11-09 19:52

import django.db.models.deletion
from django.db.models import Q
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_postings', '0001_inital_faked_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsJobDimDim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_postings.jobpostingsfact')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_postings.skillsdim')),
            ],
            options={
                'db_table': 'skills_job_dim_dim',
                'unique_together': {('job', 'skill')},
            },
        ),
    ]
